version: '3'

services:
  php-ddd-microservice-example.db:
    container_name: php-ddd-microservice-example.db
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB_DATABASE-example}
      MYSQL_USER: ${DB_USERNAME-example}
      MYSQL_PASSWORD: ${DB_PASSWORD-secret}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD-secret}
      SERVICE_NAME: mysql
      SERVICE_TAGS: dev
    image: mysql:5.7
    networks:
      - php-ddd-microservice-example
    restart: unless-stopped
    tty: true
    volumes:
      - php-ddd-microservice-example-dbdata:/var/lib/mysql/
      - ./etc/config/mysql/my.cnf:/etc/mysql/my.cnf

  php-ddd-microservice-example.lumen-api:
    build:
      context: .
      dockerfile: ./etc/docker/php.Dockerfile
    container_name: php-ddd-microservice-example.lumen-api
    restart: unless-stopped
    tty: true
    ports:
      - 8080:8080
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./etc/config/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    env_file:
      - .env
    depends_on:
      - php-ddd-microservice-example.db
    command: php -S php-ddd-microservice-example.lumen-api:8080 -t apps/lumen-api/public
    networks:
      - php-ddd-microservice-example

  php-ddd-microservice-example.unit-tests:
    build:
      context: .
      dockerfile: ./etc/docker/php.Dockerfile
    container_name: php-ddd-microservice-example.unit-tests
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./etc/config/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    env_file:
      - .env
    networks:
      - php-ddd-microservice-example

  php-ddd-microservice-example.shared-rabbitmq:
    container_name: php-ddd-microservice-example.shared-rabbitmq
    image: 'rabbitmq:3.7-management'
    restart: unless-stopped
    ports:
      - 5630:5672
      - ${RABBITMQ_PORT-8090}:15672
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER-example}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS-secret}

networks:
  php-ddd-microservice-example:
    driver: bridge

volumes:
  php-ddd-microservice-example-dbdata:
    driver: local
